version: '3'
services:
  laravel:
    container_name: laravel
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./laravel:/var/www/html/laravel
    ports:
      - "8080:80"
      # - "443:443"
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306